import junitparams.JUnitParamsRunner;
import junitparams.Parameters;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(JUnitParamsRunner.class)
public class DecoderTest {

    @Test
    @Parameters({
            "XXXOXOXOOO, D",
            "XOXOXOXXXOXXXOOO, 3",
            "XXXOXOXXXOXOOOXOXXXOOOXXXOOO, CAT"
    })
    public void basicTests(String encoded, String decoded) {
        Assert.assertEquals(decoded, Decoder.decode(encoded));
    }

    @Test(expected = IllegalArgumentException.class)
    public void basicTest4() {
        String encoded = "XOXOXOX/XXOXXXOOO";
        String decoded = "3";

        Assert.assertEquals(decoded, Decoder.decode(encoded));
    }

    @Test
    @Parameters({
            "XXOOXXOOOOOOXXXXXXOOXXOOOOOOXXXXXXOOOOOOXXOOOOOOXXOOXXXXXXOOXXOOXXOOOOOOXXOOXXXXXXOOXXOOXXOOOOOOXXOOXXOOOOOOXXOOXXXXXXOOXXXXXXOOXXXXXXOOOOOO, INTELLIJ",
            "XOXOXXXOXOOOXOXXXOOOXOXXXOXOOOXOXXXOOOXOXXXOXXXOOOXOXXXOOOXXXOXOXXXOXXXOOOOOOOXOXXXOXOXOOOXOXXXOOOXOXOXXXOOOXXXOXOOOXXXOXOXOOOXOXXXOXOOOXXXOXOXXXOXXXOOO, FARAWAY LAUNDRY",
            "XXXOOOXXXXXXXXXOOOXXXOOOOOOOOOXXXOOOXXXOOOXXXXXXXXXOOOOOOOOOXXXOOOXXXOOOXXXOOOOOOOOOXXXXXXXXXOOOOOOOOOXXXOOOXXXOOOOOOOOOXXXXXXXXXOOOXXXOOOXXXXXXXXXOOOXXXOOOOOOOOOOOOOOOOOOOOOXXXOOOXXXXXXXXXOOOXXXOOOOOOOOOXXXXXXXXXOOOXXXXXXXXXOOOXXXXXXXXXOOOOOOOOOXXXXXXXXXOOOXXXXXXXXXOOOXXXXXXXXXOOOOOOOOOXXXOOOXXXOOOXXXXXXXXXOOOXXXOOOOOOOOOXXXXXXXXXOOOOOOOOOXXXXXXXXXOOOXXXXXXXXXOOOXXXXXXXXXOOOOOOOOOXXXOOOXXXXXXXXXOOOXXXXXXXXXOOOXXXOOOOOOOOO, RUSTIC ROOFTOP",
            "XXXOOOXOXOXOXOOOXOXOOOXOXOXOOOOOOOXOXOOOXOXOXOOOOOOOXOXXXOOOOOOOXOXXXOXOXOOOXOXXXOOOXXXOXXXOOOXOOOXXXOXOOOXXXOOOXOXXXOOOXXXOXOXOXOOOXOXXXOXOXOOOXOOOOOOOXXXOOOXOXOXXXOOOXOXXXOXOOOXXXOXOOOOOOOXXXOXXXOXXXOOOXOXOXXXOXOOOOOOOXOOOXOXOXOXXXOOOXOOOXXXOXOOOXXXOOOXOXOXOOO, THIS IS A LAMENTABLE TURN OF EVENTS",
            "XXXXXXXXXXXXXXXOOOOOXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOXXXXXOOOOOXXXXXOOOOOOOOOOOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXOOOOOOOOOOOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXOOOOOXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOXXXXXOOOOOXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXOOOOOXXXXXOOOOOOOOOOOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOXXXXXOOOOOXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXOOOOOXXXXXOOOOOOOOOOOOOOOXXXXXOOOOOOOOOOOOOOOXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOXXXXXXXXXXXXXXXOOOOOOOOOOOOOOOXXXXXOOOOOOOOOOOOOOOXXXXXOOOOOXXXXXXXXXXXXXXXOOOOOXXXXXOOOOOOOOOOOOOOOXXXXXOOOOOXXXXXOOOOOXXXXXOOOOOOOOOOOOOOO, KIND OF A LOT OF LETTERS",
            "OOO0O0OOO0O000O0O0O0O000O0O000OOO0OOO000O000O0OOO0O000O0OOO000, CHIMERA",
            "TSTTTSTSSSTSTSTTTSSSTTTSTSSSTSTTTSSSTSTTTSTTTSSSTSTTTSSSTTTSTSTTTSTTTSSSSSSSTTTSTSSSTSTTTSSSTTTSSSTSTSTTTSSSTSTTTSTSSSTSSSSSSSTSTSTSTTTSSSTSTSTSSSSSSSTTTSTSSSTSTSTTTSSSTSTTTSTSSSTTTSSSTSTSTTTSSSTSTTTSTSSSTSSS, RUNAWAY NATURE VS NURTURE",
    })
    public void moderateTests(String encoded, String decoded) {
        Assert.assertEquals(decoded, Decoder.decode(encoded));
    }

    @Test
    @Parameters({
            "EEEIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEIIIIIIIIIEEEIIIEEEEEEEEEIIIEEEIIIEEEIIIIIIIIIEEEIIIEEEIIIEEEEEEEEEIIIIIIIIIEEEIIIEEEIIIEEEIIIIIIIIIEEEIIIEEEIIIEEEIIIEEEIIIIIIIIIIIIIIIIIIIIIEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEIIIIIIIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIIIIIIIEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEIIIIIIIIIEEEIIIEEEIIIEEEIIIIIIIIIIIIIIIIIIIIIEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEIIIIIIIIIEEEIIIEEEEEEEEEIIIEEEIIIEEEIIIIIIIIIEEEIIIEEEEEEEEEIIIIIIIIIEEEEEEEEEIIIEEEIIIIIIIIIIIIIIIIIIIIIEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEIIIIIIIIIEEEIIIEEEIIIEEEEEEEEEIIIIIIIIIEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEIIIIIIIIIEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEIIIIIIIIIEEEEEEEEEIIIEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIIIIIIIIIIIIIIIIIIIEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEIIIIIIIIIEEEEEEEEEIIIEEEEEEEEEIIIEEEEEEEEEIIIIIIIIIEEEEEEEEEIIIEEEIIIEEEEEEEEEIIIIIIIIIEEEIIIIIIIIIEEEIIIEEEIIIEEEIIIIIIIII, PLUSH POPS PLAN PUPPY POKES",
            "RPPPRPPPRPRPRRRRRRRRRR, Z",
            "RRRRRRRRRRPPPPPPRRPPRRPPPPPPRRRRRRPPPPPPRRPPPPPPRRPPPPPPRRRRRRPPRRPPPPPPRRRRRRPPRRPPPPPPRRPPRRPPRRRRRRPPRRPPPPPPRRRRRRRRRR, KOALA",
            "OOOOOOOOOOOOOOOQQQQQQQQQOOOQQQOOOQQQQQQQQQOOOOOOOOOQQQQQQQQQOOOQQQQQQQQQOOOQQQQQQQQQOOOOOOOOOQQQOOOQQQQQQQQQOOOOOOOOOQQQOOOQQQQQQQQQOOOQQQOOOQQQOOOOOOOOOQQQOOOQQQQQQQQQOOOOOOOOOQQQOOOQQQOOOQQQOOOOOOOOOOOOOOOOOOOOOQQQOOOQQQQQQQQQOOOOOOOOOQQQOOOQQQQQQQQQOOOQQQOOOOOOOOOQQQOOOOOOOOOOOOOOOOOOOOOQQQQQQQQQOOOQQQOOOOOOOOOQQQQQQQQQOOOQQQQQQQQQOOOQQQQQQQQQOOOOOOOOOQQQQQQQQQOOOOOOOOOOOOOOOOOOOOOQQQQQQQQQOOOQQQOOOQQQOOOQQQOOOOOOOOOQQQOOOOOOOOOQQQOOOQQQQQQQQQOOOOOOOOOQQQOOOQQQQQQQQQOOOQQQOOOOOOOOOQQQOOOQQQOOOQQQOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO, KOALAS ARE NOT BEARS",
            "",
    })
    public void advancedTests(String encoded, String decoded) {
        Assert.assertEquals(decoded, Decoder.decode(encoded));
    }

}